# Generated by Django 4.2.3 on 2023-08-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='Task_name_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='Task_name_ru',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='Task_name_uz',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
